# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arbitergrpc.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "dtkarbiterservice.ProviderRequestMessage" do
    optional :message, :string, 1
  end
  add_message "dtkarbiterservice.ArbiterResponseMessage" do
    optional :message, :string, 1
  end
end

module Dtkarbiterservice
  ProviderRequestMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("dtkarbiterservice.ProviderRequestMessage").msgclass
  ArbiterResponseMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("dtkarbiterservice.ArbiterResponseMessage").msgclass
end
